# Generated by Django 4.2.7 on 2024-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_delete_deliveryorder_delete_exchangerates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
