# Generated by Django 4.2.7 on 2024-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_animalform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalform',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
