# Generated by Django 4.2.7 on 2024-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_animalform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='client_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animalform',
            name='problem',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='animalform',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
