# Generated by Django 4.2.7 on 2024-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_animalform_client_name_alter_animalform_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
