# Generated by Django 4.2.7 on 2024-05-01 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_animalform_email_alter_animalform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='form_submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
