# Generated by Django 4.2.7 on 2024-05-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_animalform_form_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalform',
            old_name='form_submission_date',
            new_name='date',
        ),
    ]
