# Generated by Django 4.2.7 on 2024-05-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_form_submission_date_animalform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pictures/'),
        ),
        migrations.AddField(
            model_name='animalform',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pictures/'),
        ),
        migrations.AddField(
            model_name='animalform',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pictures/'),
        ),
    ]
