# Generated by Django 4.2.7 on 2024-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_animalform_picture1_animalform_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nom_clinique',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
