# Generated by Django 4.2.7 on 2024-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_account_nom_clinique'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
