# Generated by Django 4.2.7 on 2024-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='num_ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
