# Generated by Django 4.2.7 on 2024-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_account_num_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='form_picture',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pictures/'),
        ),
        migrations.AddField(
            model_name='animalform',
            name='probleme',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
