# Generated by Django 4.2.7 on 2024-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_animalform_form_picture_animalform_probleme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalform',
            name='form_picture',
        ),
        migrations.AddField(
            model_name='animalform',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/img/Dr.Beligh_1.jpg', upload_to='profile_pics/'),
        ),
    ]
