# Generated by Django 4.2.7 on 2024-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_remove_animalform_form_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalform',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='animalform',
            name='form_picture',
            field=models.ImageField(blank=True, null=True, upload_to='animal_pictures/'),
        ),
    ]
