# Generated by Django 4.2.7 on 2024-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_remove_animalform_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='status_feedback',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
