# Generated by Django 4.2.7 on 2024-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_animalform_status_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalform',
            name='status_feedback',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
