# Generated by Django 4.2.7 on 2024-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_animalform_feedback_text_animalform_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='clinic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
