# Generated by Django 4.2.7 on 2024-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_animalform_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AddField(
            model_name='account',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
