# Generated by Django 4.2.7 on 2024-06-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
