# Generated by Django 4.2.7 on 2024-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_alter_help_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalform',
            name='viewed',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
