# Generated by Django 4.2.7 on 2024-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_animalform_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='animall_examined',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
